version: "3.4"
services:
  grey-ooo:
    image: ghcr.io/matthewbaggett/grey.ooo
    build:
      context: .
    environment:
      LETSENCRYPT_DOMAINS: grey.ooo
      LETSENCRYPT_EMAIL: matthew@baggett.me
      LETSENCRYPT_MODE: "production"
    ports:
      - 80:80
      - 443:443